import pptxgen from 'pptxgenjs';

const ACCENT = '2563EB';
const ACCENT_LIGHT = 'DBEAFE';
const INK = '111827';
const SUBTLE = '6B7280';
const BORDER = 'E5E7EB';

function shadow() {
  // pptxgenjs mutates option objects in place - always build a fresh one per call
  return { type: 'outer' as const, color: '000000', blur: 6, offset: 2, angle: 135, opacity: 0.12 };
}

function accentBar(x: number, y: number, h: number, slide: pptxgen.Slide) {
  slide.addShape(pptxgen.shapes.RECTANGLE, { x, y, w: 0.08, h, fill: { color: ACCENT } });
}

interface Section {
  heading: string;
  bullets: string[];
  paragraphs: string[];
}

function parseMarkdown(content: string): { title: string; sections: Section[] } {
  const lines = content.split('\n').map(l => l.trim());
  let title = '';
  const sections: Section[] = [];
  let current: Section | null = null;

  for (const line of lines) {
    if (!line) continue;
    if (line.startsWith('# ')) {
      title = line.replace(/^#\s+/, '');
    } else if (line.startsWith('## ')) {
      const heading = line.replace(/^##\s*\d*\.?\s*/, '');
      current = { heading, bullets: [], paragraphs: [] };
      sections.push(current);
    } else if (line.startsWith('- ') || line.startsWith('* ') || /^\d+\.\s/.test(line)) {
      const text = line.replace(/^[-*]\s+/, '').replace(/^\d+\.\s+/, '');
      current?.bullets.push(text);
    } else if (current) {
      current.paragraphs.push(line);
    }
  }
  return { title: title || '기획서', sections };
}

// 최대 8개 불릿을 넘어가면 같은 섹션을 여러 슬라이드로 나눈다 (텍스트 잘림 방지)
function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

export const generateProposalPPT = async (meetingTitle: string, proposalContent: string, date: string) => {
  const pptx = new pptxgen();

  pptx.author = 'Hey Zzabi AI';
  pptx.company = 'Hey Zzabi';
  pptx.title = `기획서 - ${meetingTitle}`;
  pptx.layout = 'LAYOUT_16x9';

  pptx.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      { rect: { x: 0, y: 0, w: '100%', h: 0.45, fill: { color: ACCENT } } },
      { text: { text: 'Hey Zzabi AI Agent', options: { x: 0.4, y: 0.08, w: 4, h: 0.3, color: 'FFFFFF', fontSize: 11, bold: true, margin: 0 } } },
      { text: { text: date, options: { x: 7.2, y: 0.08, w: 2.4, h: 0.3, color: 'FFFFFF', fontSize: 9, align: 'right', margin: 0 } } },
      { rect: { x: 0, y: 5.35, w: '100%', h: 0.275, fill: { color: 'F9FAFB' } } },
      { text: { text: 'CONFIDENTIAL', options: { x: 0.4, y: 5.37, w: 3, h: 0.2, color: '9CA3AF', fontSize: 7, margin: 0 } } },
    ],
  });

  const { title, sections } = parseMarkdown(proposalContent);

  // Title slide
  const titleSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  titleSlide.addShape(pptxgen.shapes.RECTANGLE, { x: 0.5, y: 2.0, w: 0.08, h: 1.6, fill: { color: ACCENT } });
  titleSlide.addText('PROJECT PROPOSAL', { x: 0.75, y: 2.0, w: 8, h: 0.4, fontSize: 13, color: ACCENT, bold: true, charSpacing: 2, margin: 0 });
  titleSlide.addText(meetingTitle, { x: 0.75, y: 2.4, w: 8.7, h: 1.2, fontSize: 30, color: INK, bold: true, margin: 0 });
  titleSlide.addText(title !== meetingTitle ? title : 'Generated by Hey Zzabi AI Pipeline', { x: 0.75, y: 3.55, w: 8, h: 0.4, fontSize: 13, color: SUBTLE, margin: 0 });

  // Agenda slide (overview of sections)
  if (sections.length > 0) {
    const agenda = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
    agenda.addText('목차', { x: 0.5, y: 0.75, w: 8, h: 0.5, fontSize: 20, color: INK, bold: true, margin: 0 });
    sections.forEach((s, i) => {
      const y = 1.5 + i * 0.55;
      agenda.addShape(pptxgen.shapes.OVAL, { x: 0.5, y, w: 0.35, h: 0.35, fill: { color: ACCENT_LIGHT }, line: { color: ACCENT, width: 1 } });
      agenda.addText(String(i + 1), { x: 0.5, y, w: 0.35, h: 0.35, fontSize: 12, color: ACCENT, bold: true, align: 'center', valign: 'middle', margin: 0 });
      agenda.addText(s.heading, { x: 1.05, y: y + 0.02, w: 7.5, h: 0.35, fontSize: 14, color: INK, valign: 'middle', margin: 0 });
    });
  }

  // Section slides
  sections.forEach((section, sIdx) => {
    const bulletChunks = section.bullets.length > 0 ? chunk(section.bullets, 8) : [[]];

    bulletChunks.forEach((bulletChunk, chunkIdx) => {
      const slide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
      accentBar(0.5, 0.75, 0.5, slide);
      const headingSuffix = bulletChunks.length > 1 ? ` (${chunkIdx + 1}/${bulletChunks.length})` : '';
      slide.addText(`${String(sIdx + 1).padStart(2, '0')}`, { x: 0.7, y: 0.75, w: 0.7, h: 0.5, fontSize: 12, color: ACCENT, bold: true, margin: 0 });
      slide.addText(section.heading + headingSuffix, { x: 0.7, y: 1.0, w: 8.6, h: 0.5, fontSize: 22, color: INK, bold: true, margin: 0 });

      let y = 1.75;
      if (chunkIdx === 0 && section.paragraphs.length > 0) {
        slide.addText(section.paragraphs.join(' '), { x: 0.7, y, w: 8.6, h: 0.8, fontSize: 12, color: SUBTLE, margin: 0, valign: 'top' });
        y += Math.min(0.9, 0.3 + section.paragraphs.join(' ').length / 140 * 0.3);
      }

      if (bulletChunk.length > 0) {
        slide.addShape(pptxgen.shapes.RECTANGLE, {
          x: 0.7, y, w: 8.6, h: 5.15 - y,
          fill: { color: 'FFFFFF' }, line: { color: BORDER, width: 1 }, shadow: shadow(),
        });
        const bulletItems = bulletChunk.map((b, i) => ({
          text: b,
          options: { bullet: { code: '25AA' }, breakLine: i < bulletChunk.length - 1, color: '374151', paraSpaceAfter: 10 },
        }));
        slide.addText(bulletItems, { x: 1.0, y: y + 0.25, w: 8.0, h: 5.15 - y - 0.5, fontSize: 13, valign: 'top' });
      }
    });
  });

  // Closing slide
  const closing = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  closing.addText('감사합니다', { x: 0.5, y: 2.3, w: 8.5, h: 0.8, fontSize: 26, color: INK, bold: true, align: 'center', margin: 0 });
  closing.addText('Hey Zzabi AI 파이프라인이 자동 생성한 기획서입니다.', { x: 0.5, y: 3.1, w: 8.5, h: 0.4, fontSize: 12, color: SUBTLE, align: 'center', margin: 0 });

  const safeTitle = meetingTitle.replace(/[^a-zA-Z0-9가-힣]/g, '_');
  await pptx.writeFile({ fileName: `기획서_${safeTitle}_${date}.pptx` });
};
