import pptxgen from 'pptxgenjs';

export const generateProposalPPT = async (meetingTitle: string, proposalContent: string, date: string) => {
  const pptx = new pptxgen();

  // Set PPT metadata
  pptx.author = 'Hey Zzabi AI';
  pptx.company = 'Hey Zzabi';
  pptx.title = `기획서 - ${meetingTitle}`;
  pptx.layout = 'LAYOUT_16x9';

  // Master Slide Definition
  pptx.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: 'FFFFFF' },
    objects: [
      { rect: { x: 0, y: 0, w: '100%', h: 0.5, fill: { color: '2563EB' } } },
      { text: { text: 'Hey Zzabi AI Agent', options: { x: 0.5, y: 0.1, w: 3, h: 0.3, color: 'FFFFFF', fontSize: 12, bold: true } } },
      { text: { text: date, options: { x: '80%', y: 0.1, w: 2, h: 0.3, color: 'FFFFFF', fontSize: 10, align: 'right' } } },
      { rect: { x: 0, y: '95%', w: '100%', h: '5%', fill: { color: 'F3F4F6' } } },
      { text: { text: 'CONFIDENTIAL', options: { x: 0.5, y: '95.5%', w: 3, h: 0.2, color: '9CA3AF', fontSize: 8 } } },
    ],
  });

  // Title Slide
  const slide1 = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  slide1.addText('Project Proposal', { x: 0.5, y: 1.5, w: '90%', h: 0.5, fontSize: 16, color: '3B82F6', bold: true });
  slide1.addText(meetingTitle, { x: 0.5, y: 2.0, w: '90%', h: 1.5, fontSize: 32, color: '111827', bold: true });
  slide1.addText('Generated by Hey Zzabi AI Pipeline', { x: 0.5, y: 3.5, w: '90%', h: 0.5, fontSize: 14, color: '6B7280' });

  // Parse proposal content (Very simple parsing by lines and markdown hashes)
  const lines = proposalContent.split('\n').map(l => l.trim()).filter(l => l);
  
  let currentSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
  let yPos = 1.0;
  
  for (const line of lines) {
    if (yPos > 4.5) {
      currentSlide = pptx.addSlide({ masterName: 'MASTER_SLIDE' });
      yPos = 1.0;
    }

    if (line.startsWith('## ')) {
      currentSlide.addText(line.replace('## ', ''), { x: 0.5, y: yPos, w: '90%', h: 0.5, fontSize: 20, color: '1F2937', bold: true });
      yPos += 0.6;
    } else if (line.startsWith('### ')) {
      currentSlide.addText(line.replace('### ', ''), { x: 0.5, y: yPos, w: '90%', h: 0.4, fontSize: 16, color: '374151', bold: true });
      yPos += 0.5;
    } else if (line.startsWith('- ')) {
      currentSlide.addText(line.replace('- ', '• '), { x: 0.8, y: yPos, w: '85%', h: 0.3, fontSize: 12, color: '4B5563' });
      yPos += 0.4;
    } else if (line.startsWith('# ')) {
       // Main title already handled, just skip or add smaller
       currentSlide.addText(line.replace('# ', ''), { x: 0.5, y: yPos, w: '90%', h: 0.6, fontSize: 24, color: '111827', bold: true });
       yPos += 0.7;
    } else {
      currentSlide.addText(line, { x: 0.5, y: yPos, w: '90%', h: 0.3, fontSize: 12, color: '4B5563' });
      yPos += 0.4;
    }
  }

  // Generate and download
  const safeTitle = meetingTitle.replace(/[^a-zA-Z0-9가-힣]/g, '_');
  await pptx.writeFile({ fileName: `기획서_${safeTitle}_${date}.pptx` });
};
